Repository Yanol-Market/frontend, pull requests merged in 2024-01, with the labels that each got.

#14 Feat: 로그인/회원가입 목서버 셋팅
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  public/assets/images/rightArrow.svg
  public/assets/images/rightArrowTab.svg
  public/assets/images/yaLogo.svg
  src/App.test.tsx
  src/App.tsx
  src/apis/axios.ts
  src/apis/signin.ts
  src/apis/signup.ts
  src/mocks/handlers.js
  src/pages/mypage/MyPage.page.tsx
  src/pages/mypage/component/AfterSignInMyPage.tsx
  src/pages/mypage/component/BeforeSignInMyPage.tsx
  src/pages/mypage/index.ts
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/tests/signin.test.tsx
Labels: enhancement

#17 Feat: 공통 헤더 UI 생성
  package-lock.json
  package.json
  src/component/common/Header/Header.tsx
  src/pages/main/Main.page.tsx
  tailwind.config.js
Labels: enhancement

#21 Feat: 메인화면 기능 제외 퍼블리싱
  package-lock.json
  package.json
  public/assets/fonts/Pretendard-SemiBold.ttf
  public/assets/fonts/Pretendard-medium.ttf
  public/assets/fonts/Pretendard-regular.ttf
  public/assets/images/back.svg
  public/assets/images/bottomArrow.svg
  public/assets/images/buttonAlram.svg
  public/assets/images/chatLogo.svg
  public/assets/images/fire.svg
  public/assets/images/heart.svg
  public/assets/images/heart_2.svg
  public/assets/images/homeMainLogo.svg
  public/assets/images/key.svg
  public/assets/images/light.svg
  public/assets/images/productImg.jpg
  public/assets/images/searchIcon.svg
  public/assets/images/star.svg
  src/App.tsx
  src/apis/home.ts
  src/component/common/Layout/Layout.tsx
  src/component/common/Navigation/Navigation.tsx
  src/index.css
  src/mocks/handlers.js
  src/pages/localSearch/LocalSearch.page.tsx
  src/pages/localSearch/index.ts
  src/pages/main/Main.page.tsx
  src/pages/main/component/HomeContent/HomeContentTitle.tsx
  src/pages/main/component/HomeContent/index.tsx
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/main/component/HomeHeader/HomeHeader.tsx
  src/pages/main/component/HomeHeader/SearchBar.tsx
  src/pages/main/component/PlusButton/index.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListPopular.tsx
  src/pages/main/component/Product/ProductListRental.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  tailwind.config.js
Labels: enhancement

#26 Feat: 알림 페이지 UI 생성
  src/App.tsx
  src/pages/alarm/Alarm.page.tsx
  src/pages/alarm/component/Message.tsx
  src/pages/alarm/component/NewMessage.tsx
  src/pages/alarm/index.ts
Labels: enhancement

#31 Fix: app.tsx 충돌 수정
  src/App.tsx
Labels: bug

#38 Feat: 마이페이지 페이지 연결 및 디자인 수정
  package-lock.json
  package.json
  src/App.tsx
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/BottomSheet/Content/ContentFailBtnPage.tsx
  src/component/common/BottomSheet/Content/ContentTwoBtnPage.tsx
  src/component/common/Comfirm/ConfirmPage.tsx
  src/pages/mypage/MyPage.page.tsx
  src/pages/mypage/component/Account/AddMyAccount.tsx
  src/pages/mypage/component/Account/ManageAccount.tsx
  src/pages/mypage/component/Account/MyAccount.tsx
  src/pages/mypage/component/ConfirmPassword.tsx
  src/pages/mypage/component/ConfirmWithdrawl.tsx
  src/pages/mypage/component/Content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/Edit/EditPassword.tsx
  src/pages/mypage/component/Edit/ProfileEdit.tsx
  src/pages/mypage/component/ManageAccount.tsx
  src/pages/mypage/component/MyAccount.tsx
  src/pages/mypage/component/NotConfirmedPassword.tsx
  src/pages/mypage/component/Region/InterestRegion.tsx
  src/pages/mypage/component/Region/SelectBanks.tsx
  src/pages/mypage/component/RemoveAccount.tsx
  src/pages/mypage/component/SignIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/SignIn/BeforeSignInMyPage.tsx
  src/pages/mypage/component/SignOutContent.tsx
  src/pages/mypage/component/Wishes/WishList.tsx
  src/pages/mypage/component/WithDrawl/Withdrawal.tsx
  src/pages/mypage/component/WithDrawl/WithdrawlReasons.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/tests/mypage.test.tsx
  src/tests/signin.test.tsx
  tailwind.config.js
Labels: enhancement

#39 Feat : 판매내역 UI 구현
  public/assets/images/delete.svg
  public/assets/images/userDefault.svg
  src/App.tsx
  src/component/common/Header/Header.tsx
  src/component/common/Layout/Layout.tsx
  src/pages/alarm/component/Alarm.page.tsx
  src/pages/alarm/component/Message.tsx
  src/pages/alarm/index.ts
  src/pages/mypage/component/purchaseHistory/Bought.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseHistory.tsx
  src/pages/mypage/component/salesHistory/BuyProduct.tsx
  src/pages/mypage/component/salesHistory/Buyer.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/SalesProduct.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/Sold.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  tailwind.config.js
Labels: enhancement

#42 Fix : 파일 구조 경로 변경
  src/App.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/salesHistory/Sold.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/mypage/component/withDrawl/WithdrawlReasons.tsx
Labels: bug

#44 Fix :파일명 수정
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
Labels: bug

#45 Feat: 로그인/회원가입 기능 구현
  package-lock.json
  package.json
  src/component/common/Navigation/Navigation.tsx
  src/mocks/handlers.js
  src/pages/mypage/MyPage.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/tests/mypage.test.tsx
  src/tests/signin.test.tsx
Labels: enhancement

#46 Feat: 상품 등록 페이지 퍼블리싱
  public/assets/images/check.svg
  public/assets/images/yanoljaLogo.svg
  src/App.tsx
  src/component/common/Navigation/Navigation.tsx
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/AddProductHeader.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/infoInputStep/CommissionInfo.tsx
  src/pages/addProduct/component/infoInputStep/GoldenPriceDecision.tsx
  src/pages/addProduct/component/infoInputStep/SellerInfoInput.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/selectionStep/ReservationItem.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/checked.svg
  src/pages/addProduct/component/termsAndPolicyStep/unchecked.svg
  src/pages/addProduct/index.ts
Labels: enhancement

#48 Feat: 검색결과페이지 퍼블리싱
  public/assets/images/arrowTop.svg
  public/assets/images/search-m.svg
  src/App.tsx
  src/pages/main/component/HomeHeader/HomeHeader.tsx
  src/pages/main/component/HomeHeader/SearchBar.tsx
  src/pages/searchResult/SearchResult.page.tsx
  src/pages/searchResult/component/SearchResultBar.tsx
  src/pages/searchResult/component/SearchResultContent.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/pages/searchResult/index.ts
Labels: enhancement

#53 Feat: 상세페이지 퍼블리싱
  public/assets/images/chat.svg
  public/assets/images/headrt_xl.svg
  public/assets/images/location_sm.svg
  public/assets/images/locked.svg
  public/assets/images/warning.svg
  src/App.tsx
  src/apis/home.ts
  src/mocks/handlers.js
  src/pages/products/Products.page.tsx
  src/pages/products/component/DetailContent.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/products/index.ts
Labels: enhancement

#54 Feat: 나의 거래 페이지 퍼블리싱
  public/assets/images/chatLogoActive.svg
  src/App.tsx
  src/component/common/Layout/Layout.tsx
  src/component/common/Navigation/Navigation.tsx
  src/component/common/Navigation/index.ts
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatList.tsx
  src/pages/chatList/component/FilterDropdown.tsx
  src/pages/chatList/index.ts
Labels: enhancement

#55 Feat : 구매내역 페이지 UI
  public/assets/images/ic.svg
  public/assets/images/ticket.svg
  public/assets/images/ticket_1.svg
  src/App.tsx
  src/component/common/Header/Header.tsx
  src/component/common/Layout/Layout.tsx
  src/pages/mypage/component/purchaseHistory/Bought.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseHistory.tsx
  src/pages/mypage/component/salesHistory/Buyer.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SellingBottom.tsx
  src/pages/mypage/component/salesHistory/Sold.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
Labels: enhancement

#57 Feat : 상품 수정 페이지 UI
  src/App.tsx
  src/pages/editProd/Main.page.tsx
  src/pages/editProd/component/CompletionEdit.tsx
  src/pages/editProd/component/FeeInfo.tsx
  src/pages/editProd/component/GoldenPriceInfo.tsx
  src/pages/editProd/component/SellerMessage.tsx
  src/pages/editProd/index.ts
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SellingBottom.tsx
Labels: enhancement

#62 Style: 마이페이지 스타일 수정
  src/apis/axios.ts
  src/apis/home.ts
  src/apis/signin.ts
  src/apis/signup.ts
  src/apis/wishes.ts
  src/component/common/Layout/Layout.tsx
  src/component/common/Navigation/Navigation.tsx
  src/mocks/handlers.js
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/content/NotFoundContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
Labels: enhancement

#63 feat: 채팅 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoNoti.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/ProductInfo.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/SystemMessage.tsx
  src/pages/chat/index.tsx
  src/pages/mypage/MyPage.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/reservation/index.tsx
Labels: enhancement

#68 Feat: 회원가입/로그인 api 연결
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/cookie.ts
  src/apis/email.ts
  src/apis/home.ts
  src/apis/nickname.ts
  src/apis/paymentPrepare.ts
  src/apis/paymentsDetail.ts
  src/apis/signin.ts
  src/apis/signout.ts
  src/apis/signup.ts
  src/apis/wishes.ts
  src/apis/yaSignIn.ts
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/tests/refreshToken.test.tsx
  src/utils/tokenExpireCheck.ts
  tailwind.config.js
Labels: enhancement

#72 main 최신화
  package-lock.json
  package.json
  src/App.tsx
  src/apis/axios.ts
  src/apis/cookie.ts
  src/apis/email.ts
  src/apis/home.ts
  src/apis/nickname.ts
  src/apis/paymentPrepare.ts
  src/apis/paymentsDetail.ts
  src/apis/signin.ts
  src/apis/signout.ts
  src/apis/signup.ts
  src/apis/wishes.ts
  src/apis/yaSignIn.ts
  src/component/common/Layout/Layout.tsx
  src/component/common/Navigation/Navigation.tsx
  src/mocks/handlers.js
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/infoInputStep/CommissionInfo.tsx
  src/pages/addProduct/component/infoInputStep/GoldenPriceDecision.tsx
  src/pages/addProduct/component/infoInputStep/SellerInfoInput.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/selectionStep/ReservationItem.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoNoti.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/ProductInfo.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/SystemMessage.tsx
  src/pages/chat/index.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatList.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/mypage/MyPage.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/content/NotFoundContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/index.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/tests/refreshToken.test.tsx
  src/utils/tokenExpireCheck.ts
  tailwind.config.js
Labels: enhancement

#74 Feat:메인페이지 api 연결 및 스크롤바 숨김
  public/assets/images/heart_white.svg
  src/App.css
  src/apis/home.ts
  src/index.css
  src/pages/main/component/HomeContent/index.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListPopular.tsx
  src/pages/main/component/Product/ProductListRental.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/utils/b.ts
Labels: enhancement

#76 Feat : 판매, 구매내역 msw 연결
  public/assets/images/userDefaultGray.svg
  src/App.tsx
  src/apis/axios.ts
  src/apis/purchases.ts
  src/apis/sales.ts
  src/data/purchasesData.ts
  src/data/salesData.ts
  src/hooks/useQueryPurchases.ts
  src/hooks/useQuerySales.ts
  src/mocks/handlers.js
  src/pages/mypage/component/purchaseHistory/Bought.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseHistory.tsx
  src/pages/mypage/component/salesHistory/Buyer.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/utils/formate.ts
  src/utils/translate.ts
Labels: enhancement

#77 main 최신화
  public/assets/images/heart_white.svg
  public/assets/images/userDefaultGray.svg
  src/App.css
  src/App.tsx
  src/apis/axios.ts
  src/apis/home.ts
  src/apis/purchases.ts
  src/apis/sales.ts
  src/data/purchasesData.ts
  src/data/salesData.ts
  src/hooks/useQueryPurchases.ts
  src/hooks/useQuerySales.ts
  src/index.css
  src/mocks/handlers.js
  src/pages/main/component/HomeContent/index.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListPopular.tsx
  src/pages/main/component/Product/ProductListRental.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  src/pages/mypage/component/purchaseHistory/Bought.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseHistory.tsx
  src/pages/mypage/component/salesHistory/Buyer.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/utils/b.ts
  src/utils/formate.ts
  src/utils/translate.ts
Labels: enhancement

#81 Feat: 상품 등록 페이지 api 연결
  src/apis/products.ts
  src/apis/reservations.ts
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/infoInputStep/GoldenPriceDecision.tsx
  src/pages/addProduct/component/infoInputStep/SellerInfoInput.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/selectionStep/ReservationItem.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
Labels: enhancement

#83 Feat:검색페이지 및 검색결과 페이지api연결
  public/assets/images/Property 1=Fill_heart_xl.svg
  public/assets/images/fillheart_white.svg
  public/assets/images/fillheart_xl.svg
  public/assets/images/heart_xl.svg
  src/apis/searchResult.ts
  src/apis/wish.ts
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/search/component/FormSubmit.tsx
  src/pages/search/component/SearchProduct.tsx
  src/pages/search/component/WishPriceContent.tsx
  src/pages/searchResult/SearchResult.page.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/recoil/atom.ts
  src/utils/formate.ts
Labels: enhancement

#84 Feat : 알림목록 및 홈 새알림 유무 조회 API 연결
  public/assets/images/bell_on.svg
  src/apis/alarm.ts
  src/hooks/useQuertAlarm.ts
  src/pages/alarm/Alarm.page.tsx
  src/pages/alarm/component/Alarm.page.tsx
  src/pages/alarm/component/NewMessage.tsx
  src/pages/alarm/index.ts
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/type/alarm.ts
Labels: enhancement

#86 Feat: 마이페이지 , 결제페이지 api 연결
  package-lock.json
  package.json
  public/assets/images/homeMainLogo.svg
  public/assets/images/mainLogo.svg
  public/assets/images/notFound.svg
  public/favicon1.ico
  public/index.html
  src/App.tsx
  src/apis/axios.ts
  src/apis/cookie.ts
  src/apis/deleteAccounts.ts
  src/apis/detail.ts
  src/apis/getAccounts.ts
  src/apis/getProfile.ts
  src/apis/patchAccounts.ts
  src/apis/paymentsDetail.ts
  src/component/common/NotFound/NotFound.page.tsx
  src/component/common/NotFound/index.ts
  src/data/bankLogoData.ts
  src/mocks/handlers.js
  src/pages/main/Main.page.tsx
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/content/NotFoundContent.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Total.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/signUp/component/checked.svg
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/recoil/atom.ts
Labels: enhancement

#88 Feat: 판매중 및 상품 수정 API 연결
  package-lock.json
  package.json
  public/assets/images/ic_edit.svg
  src/apis/products.ts
  src/apis/sales.ts
  src/component/common/Header/Header.tsx
  src/data/purchasesData.ts
  src/hooks/useQuertAlarm.ts
  src/pages/editProd/Main.page.tsx
  src/pages/editProd/component/FeeInfo.tsx
  src/pages/editProd/component/GoldenPriceInfo.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SellingBottom.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/recoil/prodEditAtom.ts
  src/type/product.ts
  src/utils/formate.ts
Labels: enhancement

#91 Fix : dev 병합 충돌 해결
  src/component/common/Layout/Layout.tsx
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
Labels: bug

#92 Fix : width 430px로 수정
  src/component/common/Layout/Layout.tsx
Labels: enhancement

#96 Feat: 채팅방 api 연동 1차 -네고하기
  package-lock.json
  package.json
  src/App.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoNoti.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/ProductInfo.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/SystemMessage.tsx
  src/pages/chat/index.tsx
  src/recoil/atom.ts
Labels: enhancement

#98 Feat: 나의 거래 페이지 api 연결
  src/apis/chatList.ts
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/Layout/Layout.tsx
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/AddProductHeader.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatListProd.tsx
Labels: enhancement

#100 Feat: 마이페이지 관심지역 / 회원 정보 변경 api 연결 + 야놀자 로그인
  src/apis/axios.ts
  src/apis/cookie.ts
  src/apis/email.ts
  src/apis/getInterestRegions.ts
  src/apis/nickname.ts
  src/apis/patchPassword.ts
  src/apis/postInterestRegion.ts
  src/apis/signup.ts
  src/data/regionData.ts
  src/index.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/reservation/PurchaserInfo.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/tests/refreshToken.test.tsx
  src/utils/convertRegionCode.ts
Labels: enhancement

#101 main 최신화
  package-lock.json
  package.json
  src/App.tsx
  src/apis/axios.ts
  src/apis/chatList.ts
  src/apis/cookie.ts
  src/apis/email.ts
  src/apis/getInterestRegions.ts
  src/apis/nickname.ts
  src/apis/patchPassword.ts
  src/apis/postInterestRegion.ts
  src/apis/signup.ts
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/Layout/Layout.tsx
  src/data/regionData.ts
  src/index.tsx
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/AddProductHeader.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoNoti.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/ProductInfo.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/SystemMessage.tsx
  src/pages/chat/index.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatListProd.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/reservation/PurchaserInfo.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/recoil/atom.ts
  src/tests/refreshToken.test.tsx
  src/utils/convertRegionCode.ts
Labels: enhancement

#105 Feat: 상품 등록 - 야놀자 로그인 api 연결
  src/App.tsx
  src/apis/yaSignIn.ts
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/infoInputStep/AddProductInfoInputStep.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/addProductYaSignIn/AddProductYaSignIn.page.tsx
  src/pages/addProductYaSignIn/index.ts
Labels: enhancement

#108 Feat: 마이페이지 남은 API 연결
  src/apis/axios.ts
  src/apis/deleteMember.ts
  src/apis/putNickname.ts
  src/apis/wishes.ts
  src/data/regionData.ts
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/mypage/component/withDrawl/WithdrawlReasons.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/recoil/atom.ts
Labels: enhancement

#112 Feat: 판매 및 구매 내역 페이지 API 연결
  src/apis/purchases.ts
  src/apis/sales.ts
  src/data/purchasesData.ts
  src/hooks/useQueryPurchases.ts
  src/hooks/useQuerySales.ts
  src/pages/alarm/Alarm.page.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/pages/mypage/component/salesHistory/skeleton/SellingSkeleton.tsx
  src/utils/formate.ts
  tailwind.config.js
Labels: enhancement

#113 Feat: 나의 거래 없을 경우 ui 추가
  src/apis/products.ts
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatListProd.tsx
Labels: enhancement

#114 Main 최신화
  src/apis/axios.ts
  src/apis/deleteMember.ts
  src/apis/products.ts
  src/apis/purchases.ts
  src/apis/putNickname.ts
  src/apis/sales.ts
  src/apis/wishes.ts
  src/data/purchasesData.ts
  src/data/regionData.ts
  src/hooks/useQueryPurchases.ts
  src/hooks/useQuerySales.ts
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProduct/component/termsAndPolicyStep/TermsAndPolicyAgreementStep.tsx
  src/pages/alarm/Alarm.page.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/chatList/component/ChatListProd.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/pages/mypage/component/salesHistory/skeleton/SellingSkeleton.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/mypage/component/withDrawl/WithdrawlReasons.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/recoil/atom.ts
  src/utils/formate.ts
  tailwind.config.js
Labels: enhancement

#115 Feat: 네고하기 버튼 누르면 채팅방으로 이동
  src/App.tsx
  src/index.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/products/component/ProductInfo.tsx
  src/recoil/atom.ts
Labels: enhancement

#118 Feat: 상품 등록 에러 해결
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
Labels: enhancement

#122 Feat: QA 1차 수정
  public/assets/images/chatLogo.svg
  public/assets/images/chatLogoActive.svg
  public/assets/images/fillheart_white.svg
  public/assets/images/fillheart_white_xl.svg
  public/assets/images/heart_white.svg
  public/assets/images/heart_white_xl.svg
  public/assets/images/homeLogo.svg
  public/assets/images/homeLogoActive.svg
  public/assets/images/locationLogo.svg
  public/assets/images/locationLogoActive.svg
  public/assets/images/profileLogo.svg
  public/assets/images/profileLogoActive.svg
  public/assets/images/writeLogo.svg
  public/assets/images/writeLogoActive.svg
  src/apis/axios.ts
  src/apis/wish.ts
  src/component/common/Layout/Layout.tsx
  src/pages/localSearch/LocalSearch.page.tsx
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/search/Search.page.tsx
  src/pages/search/component/SearchDate.tsx
  src/pages/search/component/SearchProduct.tsx
  src/pages/search/component/WishPriceContent.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/utils/b.ts
Labels: enhancement

#123 Feat: 결제 페이지 쿼리스트링 연결 및 비밀번호 찾기 구현
  public/index.html
  src/App.tsx
  src/apis/findEmail.ts
  src/pages/alarm/Alarm.page.tsx
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/findPassword/index.ts
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Total.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/utils/useSignInChecked.ts
Labels: enhancement

#124 Main 최신화
  public/assets/images/chatLogo.svg
  public/assets/images/chatLogoActive.svg
  public/assets/images/fillheart_white.svg
  public/assets/images/fillheart_white_xl.svg
  public/assets/images/heart_white.svg
  public/assets/images/heart_white_xl.svg
  public/assets/images/homeLogo.svg
  public/assets/images/homeLogoActive.svg
  public/assets/images/locationLogo.svg
  public/assets/images/locationLogoActive.svg
  public/assets/images/profileLogo.svg
  public/assets/images/profileLogoActive.svg
  public/assets/images/writeLogo.svg
  public/assets/images/writeLogoActive.svg
  public/index.html
  src/App.tsx
  src/apis/axios.ts
  src/apis/findEmail.ts
  src/apis/wish.ts
  src/component/common/Layout/Layout.tsx
  src/index.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/alarm/Alarm.page.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/TransferNoti.tsx
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/findPassword/index.ts
  src/pages/localSearch/LocalSearch.page.tsx
  src/pages/main/component/HomeHeader/HeaderInfo.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/main/component/Product/ProductListNew.tsx
  src/pages/main/component/Product/ProductListSpecial.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/Complete.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Total.tsx
  src/pages/search/Search.page.tsx
  src/pages/search/component/SearchDate.tsx
  src/pages/search/component/SearchProduct.tsx
  src/pages/search/component/WishPriceContent.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/recoil/atom.ts
  src/utils/b.ts
  src/utils/useSignInChecked.ts
Labels: enhancement

#129 Feat : QA 바탕으로 판매중, 구매중 ui 수정
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/Header/Header.tsx
  src/data/salesData.ts
  src/pages/alarm/Alarm.page.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
Labels: enhancement

#130 Main 최신화
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/Header/Header.tsx
  src/data/salesData.ts
  src/pages/alarm/Alarm.page.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/reservation/TermSheet.tsx
Labels: enhancement

#131 Fix : 로그인 / 회원가입 / 소셜 로그인 QA 반영 + 결제 로직 수정
  src/apis/axios.ts
  src/apis/cookie.ts
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/reservation/Payment.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Total.tsx
  src/pages/reservation/index.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
Labels: enhancement

#132 Fix: 양도 거절
  src/pages/chat/SellerChat.tsx
  src/pages/chat/TransferNoti.tsx
Labels: bug

#133 Main 최신화
  src/apis/axios.ts
  src/apis/cookie.ts
  src/pages/chat/SellerChat.tsx
  src/pages/chat/TransferNoti.tsx
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/reservation/Payment.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Total.tsx
  src/pages/reservation/index.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
Labels: enhancement

#139 Fix: 네고 패널 변경, 메시지 수신자 변경, 예약 중 상품 표기
  src/pages/chat/Chat.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/TermSheet.tsx
  src/recoil/atom.ts
Labels: enhancement

#136 Feat: 나의 거래 채팅방 연결
  src/pages/chatList/component/ChatListProd.tsx
Labels: enhancement

#141 Fix: 마이페이지 QA 반영
  package-lock.json
  package.json
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/BottomSheet/Content/ContentTwoBtnPage.tsx
  src/data/regionData.ts
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
Labels: enhancement

#142 Fix: QA 1차 수정
  public/assets/images/ic_EXPIRED.svg
  public/assets/images/ic_RESERVED.svg
  public/assets/images/ic_SOLD_OUT.svg
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/products/component/ProductInfo.tsx
Labels: bug

#143 Feat : 구매, 판매 내역 QA 버그 해결 및 스켈레톤 UI
  src/apis/purchases.ts
  src/component/common/Loading/Loading.tsx
  src/component/common/Loading/index.ts
  src/data/purchasesData.ts
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SellingBottom.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/skeleton/ListSkeleton.tsx
  src/pages/mypage/component/salesHistory/skeleton/SoldSkeleton.tsx
Labels: enhancement

#148 main 최신화
  package-lock.json
  package.json
  public/assets/images/ic_EXPIRED.svg
  public/assets/images/ic_RESERVED.svg
  public/assets/images/ic_SOLD_OUT.svg
  public/assets/images/wallet.svg
  src/apis/axios.ts
  src/apis/purchases.ts
  src/component/common/BottomSheet/BottomSheet.tsx
  src/component/common/BottomSheet/Content/ContentTwoBtnPage.tsx
  src/component/common/Loading/Loading.tsx
  src/component/common/Loading/index.ts
  src/data/purchasesData.ts
  src/data/regionData.ts
  src/index.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/AddProductHeader.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProductYaSignIn/AddProductYaSignIn.page.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chatList/component/ChatListProd.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SellingBottom.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/skeleton/ListSkeleton.tsx
  src/pages/mypage/component/salesHistory/skeleton/SoldSkeleton.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/recoil/atom.ts
Labels: enhancement

#150 Chore: README 틀 작성
  README.md
Labels: documentation

#153 Fix: QA 오류 해결
  src/App.tsx
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/TransferNoti.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/Failure.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/Timeout.tsx
  src/recoil/atom.ts
Labels: bug

#154 Feat: 마이페이지 이용약관 페이지
  public/_redirects
  public/assets/images/myprofileInfo/profile1.png
  public/assets/images/myprofileInfo/profile2.png
  public/assets/images/myprofileInfo/profile3.png
  public/assets/images/myprofileInfo/profile4.png
  public/assets/images/myprofileInfo/profile5.png
  public/assets/images/myprofileInfo/profile6.png
  src/App.tsx
  src/component/common/BottomSheet/BottomSheet.tsx
  src/data/ServiceTextData.ts
  src/data/profileServiceData.ts
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/service/ProfilePolicies.tsx
  src/pages/mypage/component/service/ServicePolicies.tsx
  src/pages/mypage/component/signIn/AfterSignInMyPage.tsx
  src/pages/mypage/component/signIn/BeforeSignInMyPage.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/reservation/TermSheet.tsx
Labels: enhancement

#155 Fix: 상품 등록/ 나의 거래 QA 반영
  src/pages/addProduct/AddProduct.page.tsx
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProductYaSignIn/AddProductYaSignIn.page.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/btn/MyPageClickBtn.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
Labels: enhancement

#156 Fix:QA 2차 수정
  package-lock.json
  package.json
  src/apis/searchResult.ts
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/search/Search.page.tsx
  src/pages/search/component/FormSubmit.tsx
  src/pages/search/component/SearchDate.tsx
  src/pages/search/component/SearchProduct.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
  src/recoil/atom.ts
Labels: enhancement

#160 Fix: 관심 지역 바텀시트 스크롤화 및 찜한 상품 상태값 보여주기 구현
  src/apis/deleteAccounts.ts
  src/apis/paymentPrepare.ts
  src/apis/signout.ts
  src/apis/signup.ts
  src/apis/wishes.ts
  src/component/common/BottomSheet/BottomSheet.tsx
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/service/ProfilePolicies.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/WithdrawlReasons.tsx
  src/pages/reservation/Failure.tsx
  src/pages/reservation/Payment.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/index.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
Labels: enhancement

#164 Fix:QA 3차 피드백 반영
  src/pages/products/component/ProductInfo.tsx
  src/pages/searchResult/component/SearchResultList.tsx
Labels: enhancement

#165 Feat : 오류 수정
  src/component/common/BottomSheet/BottomSheet.tsx
  src/hooks/a.ts
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/skeleton/SoldSkeleton.tsx
  src/tests/selling.test.tsx
Labels: bug

#166 Main 최신화
  README.md
  src/apis/deleteAccounts.ts
  src/apis/paymentPrepare.ts
  src/apis/signout.ts
  src/apis/signup.ts
  src/apis/wishes.ts
  src/component/common/BottomSheet/BottomSheet.tsx
  src/hooks/a.ts
  src/pages/chat/Chat.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatItem.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/ProductInfo.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chat/TransferNoti.tsx
  src/pages/findPassword/FindPassword.page.tsx
  src/pages/mypage/component/account/AddMyAccount.tsx
  src/pages/mypage/component/account/ManageAccount.tsx
  src/pages/mypage/component/account/MyAccount.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/edit/EditPassword.tsx
  src/pages/mypage/component/edit/ProfileEdit.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/PurchaseDetail.tsx
  src/pages/mypage/component/region/InterestRegion.tsx
  src/pages/mypage/component/region/SelectBanks.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/SalesHistory.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/skeleton/SoldSkeleton.tsx
  src/pages/mypage/component/service/ProfilePolicies.tsx
  src/pages/mypage/component/wishes/WishItem.tsx
  src/pages/mypage/component/wishes/WishList.tsx
  src/pages/mypage/component/withDrawl/WithdrawlReasons.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/reservation/Failure.tsx
  src/pages/reservation/Payment.tsx
  src/pages/reservation/Product.tsx
  src/pages/reservation/TermSheet.tsx
  src/pages/reservation/index.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/pages/signIn/SignIn.page.tsx
  src/pages/signUp/SignUp.page.tsx
  src/pages/yaSignIn/YaSignIn.page.tsx
  src/tests/selling.test.tsx
Labels: enhancement

#167 Fix:결과페이지 무한스크롤 안되는 이슈 해결
  src/pages/searchResult/component/SearchResultList.tsx
Labels: bug

#171 Fix: 관심지역 체크리스트 Recoil-persist 적용
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/recoil/atom.ts
Labels: bug

#175 Fix: 회원탈퇴 시 로컬스토리지 초기화되게 수정
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
Labels: bug

#176 Main 배포
  README.md
  image.png
  package-lock.json
  src/apis/axios.ts
  src/pages/addProduct/component/CompletionScreen.tsx
  src/pages/addProduct/component/selectionStep/AddProductSelectionStep.tsx
  src/pages/addProductYaSignIn/AddProductYaSignIn.page.tsx
  src/pages/alarm/Alarm.page.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/NegoPanel.tsx
  src/pages/chat/SellerChat.tsx
  src/pages/chatList/ChatList.page.tsx
  src/pages/editProd/Main.page.tsx
  src/pages/editProd/component/CompletionEdit.tsx
  src/pages/main/component/Product/ProductItemNew.tsx
  src/pages/main/component/Product/ProductItemPopular.tsx
  src/pages/main/component/Product/ProductItemRental.tsx
  src/pages/main/component/Product/ProductItemSpecial.tsx
  src/pages/mypage/component/content/BottomSheetRegionContent.tsx
  src/pages/mypage/component/purchaseHistory/BoughtListProd.tsx
  src/pages/mypage/component/purchaseHistory/Buying.tsx
  src/pages/mypage/component/salesHistory/CardProd.tsx
  src/pages/mypage/component/salesHistory/Chat.tsx
  src/pages/mypage/component/salesHistory/ExpiredProdDetail.tsx
  src/pages/mypage/component/salesHistory/Selling.tsx
  src/pages/mypage/component/salesHistory/SoldDetail.tsx
  src/pages/mypage/component/salesHistory/SoldListProd.tsx
  src/pages/mypage/component/salesHistory/StatusBar.tsx
  src/pages/mypage/component/withDrawl/Withdrawal.tsx
  src/pages/products/component/ProductInfo.tsx
  src/pages/searchResult/component/SearchResultList.tsx
  src/recoil/atom.ts
  src/tests/chat.test.tsx
  src/utils/tokenExpireCheck.ts
Labels: enhancement

#177 Fix: qa 3차 반영
  src/pages/products/component/ProductInfo.tsx
  src/pages/searchResult/component/SearchResultProduct.tsx
Labels: bug
